title: "Combining Multiple Trained NER Components"
description: > 
  This project shows you the different ways you can combine multiple trained
  NER components and their tradeoffs.

vars:
  name: "ner_double"
  version: "0.0.0"
  drug_model: "ner_drugs-0.0.0"

directories: ["assets", "configs", "scripts", "pipelines", "packages"]

workflows:
  all:
    - prep
    - assemble

assets:
  - dest: "assets/${vars.drug_model}.tar.gz"
    url: "https://github.com/explosion/projects/releases/download/en-ner-drugs-0.0.0/en_ner_drugs-0.0.0.tar.gz"
    checksum: "d377872a1c060db4caa686a1a3a5ddea"
    description: "Pretrained drug model"

commands:
  - name: prep
    help: "Install the base models."
    script:
      - "python -m spacy download en_core_web_md"
      - "pip install assets/${vars.drug_model}.tar.gz"
  - name: assemble
    help: "Build two versions of the combined pipelines from configs."
    script:
      - "python -m spacy assemble configs/double.cfg pipelines/drugs_first"
      - "python -m spacy assemble configs/double.cfg pipelines/drugs_second --nlp.pipeline '[\"ner\", \"ner_drug\"]'"
    outputs:
      - pipelines/drugs_first
      - pipelines/drugs_second

  - name: package
    help: "Package the pipelines so they can be installed."
    script: 
      - "python -m spacy package pipelines/drugs_first packages --name drugs_first --version ${vars.version} --force"
      - "python -m spacy package pipelines/drugs_second packages --name drugs_second --version ${vars.version} --force"
    deps:
      - pipelines/drugs_first
      - pipelines/drugs_second
    outputs_no_cache:
      - "packages/en_drugs_first-${vars.version}/dist/en_drugs_first-${vars.version}.tar.gz"
      - "packages/en_drugs_second-${vars.version}/dist/en_drugs_second-${vars.version}.tar.gz"

  - name: check
    help: "Use the pipeline interactively using Streamlit"
    script:
      - "streamlit run scripts/check.py pipelines/drugs_first,pipelines/drugs_second \"My name is John Benz and I remove weeds from my garden.\""
    deps:
      - pipelines/drugs_first
      - pipelines/drugs_second
