title: "Combining Multiple Trained NER Components"
description: > 
  This project shows you the different ways you can combine multiple trained
  NER components and their tradeoffs.

  Note that before running this project, you should run the
  [ner_drugs](../ner_drugs) project and install the packaged version of it.

vars:
  name: "ner_double"
  version: "0.0.0"
  drug_model: "ner_drugs-0.0.0"

directories: ["configs", "scripts", "pipelines", "packages"]

workflows:
  all:
    - assemble

commands:
  - name: assemble
    help: "Build two versions of the combined pipelines from configs."
    script:
      - "python -m spacy assemble configs/double.cfg pipelines/drugs_first"
      - "python -m spacy assemble configs/double.cfg pipelines/drugs_second --nlp.pipeline '[\"ner\", \"ner_drug\"]'"
    outputs:
      - pipelines/drugs_first
      - pipelines/drugs_second

  - name: package
    help: "Package the pipelines so they can be installed."
    script: 
      - "python -m spacy package pipelines/drugs_first packages --name drugs_first --version ${vars.version} --force"
      - "python -m spacy package pipelines/drugs_second packages --name drugs_second --version ${vars.version} --force"
    deps:
      - pipelines/drugs_first
      - pipelines/drugs_second
    outputs_no_cache:
      - "packages/en_drugs_first-${vars.version}/dist/en_drugs_first-${vars.version}.tar.gz"
      - "packages/en_drugs_second-${vars.version}/dist/en_drugs_second-${vars.version}.tar.gz"

  - name: check
    help: "Use the pipeline interactively using Streamlit"
    script:
      - "streamlit run scripts/check.py pipelines/drugs_first,pipelines/drugs_second \"My name is John Benz and I remove weeds from my garden.\""
    deps:
      - pipelines/drugs_first
      - pipelines/drugs_second
