title: 'NEL Benchmark'
description: "Pipeline for benchmarking NEL approaches (incl. candidate generation and entity disambiguation)."
vars:
  run: "cg-default"
  config: "nel.cfg"
  vectors_model: "en_core_web_lg"
  version: "0.0.6"
  dataset: "mewsli_9"
  gpu_id: ""
  download_all_wiki_assets: ""  # "--extra" to download full Wiki dumps.
  filter: "--filter"  # Whether to only use parts of Wiki data and corpus containing filter terms.
  training_max_steps: 1000
  eval_highlight_metric: "F"  # one of ("F", "r", "p")

directories: ["assets", "training", "configs", "scripts", "corpora", "temp", "evaluation"]

workflows:
  all:
    - download_mewsli9
    - preprocess
    - download_model
    - wiki_clone_wikid
    - wiki_download_assets
    - wiki_parse
    - parse_wiki_dumps
    - create_kb
    - compile_corpora
    - train
    - evaluate
    - compare_evaluations
  training:
    - train
    - evaluate

commands:
  - name: download_mewsli9
    help: Download Mewsli-9 dataset.
    script:
      - bash scripts/datasets/download_mewsli-9.sh
    outputs:
      - assets/mewsli_9/

  - name: preprocess
    help: Preprocess test datasets.
    script:
      - "python ./scripts/clean_data.py ${vars.dataset}"
    deps:
      - "assets/${vars.dataset}/raw"
    outputs:
      - "assets/${vars.dataset}/clean"

  - name: download_model
    help: "Download a model with pretrained vectors and NER component."
    script:
      - "python -m spacy download ${vars.vectors_model}"

  - name: wiki_clone_wikid
    help: Clone `wikid` to prepare Wiki database and `KnowledgeBase`.
    script:
      # To be updated after merge.
      - git clone https://github.com/rmitsch/wikid.git && cd wikid && git checkout feature/wiki-parsing && cd ..
      - pip install -r wikid/requirements.txt

  - name: wiki_download_assets
    help: "Download Wikipedia dumps. This can take a long time if you're not using the filtered dumps!"
    script:
      - "spacy project assets wikid ${vars.download_all_wiki_assets}"
    outputs:
      - "wikid/assets/"

  - name: wiki_parse
    help: "Parse Wikipedia dumps. This can take a long time if you're not using the filtered dumps!"
    script:
      - "spacy project run parse wikid --vars.use_filtered_dumps ${vars.filter}"
    outputs:
      - "assets/wiki/wiki.sqlite3"

  - name: create_kb
    help: "Create the knowledge base and write it to file."
    script:
      - "python ./scripts/create_kb.py ${vars.dataset} ${vars.vectors_model}"
    deps:
      - "assets/${vars.dataset}/clean"
      - "assets/wiki/wiki.sqlite3"
    outputs:
      - "assets/${vars.dataset}/entities.pkl"
      - "assets/${vars.dataset}/entities_failed_lookup.pkl"
      - "assets/${vars.dataset}/annotations.pkl"
    outputs_no_cache:
      - "temp/${vars.dataset}/kb"
      - "temp/${vars.dataset}/nlp"

  - name: compile_corpora
    help: "Compile corpora, separated in train/dev/test sets."
    script:
      - "python ./scripts/compile_corpora.py ${vars.dataset} ${vars.filter}"
    deps:
      - "assets/${vars.dataset}/entities.pkl"
      - "assets/${vars.dataset}/entities_failed_lookups.pkl"
      - "assets/${vars.dataset}/annotations.pkl"
      - "temp/${vars.dataset}/kb"
      - "temp/${vars.dataset}/nlp"
      - "configs/datasets.yml"
    outputs:
      - "corpora/${vars.dataset}/train.spacy"
      - "corpora/${vars.dataset}/dev.spacy"
      - "corpora/${vars.dataset}/test.spacy"

  - name: train
    help: "Train a new Entity Linking component. Pass --vars.gpu_id GPU_ID to train with GPU. Training with some datasets may take a long time!"
    script:
      - "bash scripts/train.sh ${vars.dataset} '${vars.run}' ${vars.config} ${vars.training_max_steps} ${vars.gpu_id}"
    outputs:
      - "training/${vars.dataset}/${vars.run}"
    deps:
      - "temp/${vars.dataset}/kb"
      - "temp/${vars.dataset}/nlp"
      - "corpora/${vars.dataset}/train.spacy"
      - "corpora/${vars.dataset}/dev.spacy"

  - name: evaluate
    help: "Evaluate on the test set."
    script:
      - "env PYTHONPATH=. python ./scripts/evaluate.py ${vars.dataset} '${vars.run}'"
    deps:
      - "training/${vars.dataset}/${vars.run}/model-best"
      - "temp/${vars.dataset}/nlp"
      - "corpora/${vars.dataset}/dev.spacy"
    outputs:
      - "evaluation/${vars.dataset}"

  - name: compare_evaluations
    help: "Compare available set of evaluation runs."
    script:
      - "env PYTHONPATH=. python ./scripts/compare_evaluations.py ${vars.dataset} --highlight-criterion ${vars.eval_highlight_metric}"
    deps:
      - "evaluation/${vars.dataset}"

  - name: delete_wiki_db
    help: "Deletes SQLite database generated in step parse_wiki_dumps with data parsed from Wikidata and Wikipedia dump."
    script:
      - "rm -f assets/wiki/wiki.sqlite3"
    deps:
      - "assets/wiki/wiki.sqlite3"

  - name: clean
    help: "Remove intermediate files for specified dataset (excluding Wiki resources and database)"
    script:
      - "rm -rf training/${vars.dataset}"
      - "rm -rf corpora/${vars.dataset}"
      - "rm -rf temp/${vars.dataset}"
      - "rm -rf assets/${vars.dataset}"
      - "rm -rf evaluation/${vars.dataset}"
