name: tests

on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths-ignore:
      - "*.md"

env:
  # Make sure we're exiting training as early as possible
  SPACY_CONFIG_OVERRIDES: '--training.max_epochs=1 --training.max_steps=1'
  WEASEL_CONFIG_OVERRIDES: '--training.max_epochs=1 --training.max_steps=1'
  WASABI_LOG_FRIENDLY: 1

jobs:
  tests:
    name: Test
    if: github.repository_owner == 'explosion'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            python_version: "3.8"
          - os: ubuntu-20.04
            python_version: "3.8"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Configure Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests
        shell: bash
        run: |
          bash run-tests.sh python
